# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # ğŸ”¹ Pod-level securityContext: container ì•„ë‹Œ pod ë°”ë¡œ ì•„ë˜ì—
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 101
      containers:
        - name: frontend
          image: {{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          # ğŸ”¹ container-level securityContext ìµœì†Œí™”
          securityContext:
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN              # chown ê¶Œí•œ ì¶”ê°€
                - NET_BIND_SERVICE   # 80, 443 ë“± ë‚®ì€ ë²ˆí˜¸ì˜ í¬íŠ¸ë¥¼ ì‚¬ìš©í•˜ê¸° ìœ„í•œ ê¶Œí•œ
                - SETGID
                - SETUID
          env:
            - name: REACT_APP_BACKEND_URL
              value: {{ .Values.env.frontend.VUE_APP_BACKEND_URL | quote }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: run-volume
              mountPath: /var/run
            - name: cache-volume
              mountPath: /var/cache/nginx
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
